version: '3.8'
services:
  app:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:latest
    container_name: Franklin
    environment:
      POSTGRES_USER: Frank
      POSTGRES_PASSWORD: frankfrank
      POSTGRES_DB: FrankEx
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
